---
title: "resampling"
author: "Wayne Lee"
date: "2/2/2021"
output: html_document
---

## Please download the "tweet_token_freq.csv"

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tweets in Jan 2021

```{r}
df <- read.csv("~/repos/leewtai.github.io/courses/data_mining/labs/small_non_retweets_dc_inaug_steal.csv")
head(df, 2)
```

## A basic model

```{r}
df$steal_flag <- as.numeric(df$steal_flag == "True")
# head(df[df$steal_flag > 0 , "text"], 4)
mean(df$steal_flag)
pos_ind <- which(df$steal_flag > 0)
N <- length(pos_ind) * 10
sample_ind <- sample(pos_ind, N, replace=TRUE)

# df is NOT overwritten!
new_df <- rbind(df[sample_ind, ], df)
ols <- lm(steal_flag ~ trump + capitol.police, data=new_df)
```

- Up-sampling is a hack to make the objective function, give more weight to the positive yet rare cases!

## bootstrap!

```{r}
B <- 100

coeffs <- matrix(NA, nrow=B, ncol=3)
for(i in seq_len(B)){
  boot_ind <- sample(nrow(df), nrow(df), replace=TRUE)
  boot_df <- df[boot_ind, ]
  boot_ols <- lm(steal_flag ~ trump + capitol.police, data=boot_df)
  coeffs[i, ] <- boot_ols$coefficients
}
hist(coeffs[, 2])
```

```{r}
k <- 5
# Make sure each split, has roughly the same number of records!
test_inds <- rep(1:k, nrow(df) / k)
# Make sure things are random, no bias!
test_inds <- sample(test_inds)

```